object Versions {
  lazy val akkaPersistenceS3Version = "1.0.16"
  lazy val keyManagementVersion     = "0.1.0-SNAPSHOT"
  lazy val agreementProcessVersion  = "0.1.0-SNAPSHOT"
  lazy val vaultDriverVersion       = "5.1.0"
  lazy val scalaMockVersion         = "5.1.0"
  lazy val stateMonitoringVersion   = "0.0.3-SNAPSHOT"
  lazy val akkaVersion              = "2.6.15"
  lazy val akkaHttpVersion          = "10.2.4"
  lazy val json4sVersion            = "4.0.0"
  lazy val kamonVersion             = "2.2.0"
  lazy val logbackVersion           = "1.2.3"
  lazy val scalatestVersion         = "3.2.8"
  lazy val mockitoVersion           = "3.9.0"
  lazy val catsVersion              = "2.6.0"
  lazy val nimbusVersion            = "9.10.1"
  lazy val bouncycastleVersion      = "1.69"
  lazy val jacksonVersion           = "2.11.4"
}
