/**
 * Security Process Micro Service
 * This service is the security supplier
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model

import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.ApiModel

case class ClientCredentialsResponse (
  access_token: String,
  token_type: ClientCredentialsResponseEnums.TokenType,
  expires_in: Long
) extends ApiModel

object ClientCredentialsResponseEnums {

  type TokenType = TokenType.Value
  object TokenType extends Enumeration {
    val Bearer = Value("Bearer")
    val Pop = Value("Pop")
  }

}

