/**
 * Security Process Micro Service
 * This service is the security supplier
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model

import java.util.UUID
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.ApiModel

case class Client (
  id: UUID,
  eservice: EService,
  consumer: Organization,
  agreement: Agreement,
  name: String,
  purposes: String,
  description: Option[String] = None,
  status: ClientEnums.Status,
  operators: Option[Seq[Operator]] = None
) extends ApiModel

object ClientEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Active = Value("active")
    val Suspended = Value("suspended")
  }

}

