/**
 * Security Process Micro Service
 * This service is the security supplier
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model

import java.util.UUID
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.ApiModel

case class EService (
  id: UUID,
  name: String,
  provider: Organization,
  activeDescriptor: Option[Descriptor] = None
) extends ApiModel


