/**
 * Security Process Micro Service
 * This service is the security supplier
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model

import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.ApiModel

case class Key (
  kty: String,
  key_ops: Option[Seq[String]] = None,
  use: Option[String] = None,
  alg: Option[String] = None,
  kid: String,
  x5u: Option[String] = None,
  x5t: Option[String] = None,
  x5tS256: Option[String] = None,
  x5c: Option[Seq[String]] = None,
  crv: Option[String] = None,
  x: Option[String] = None,
  y: Option[String] = None,
  d: Option[String] = None,
  k: Option[String] = None,
  n: Option[String] = None,
  e: Option[String] = None,
  p: Option[String] = None,
  q: Option[String] = None,
  dp: Option[String] = None,
  dq: Option[String] = None,
  qi: Option[String] = None,
  oth: Option[Seq[OtherPrimeInfo]] = None
) extends ApiModel


