/**
 * Security Process Micro Service
 * This service is the security supplier
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model

import java.time.OffsetDateTime
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.ApiModel

case class ValidJWT (
  iss: String,
  sub: String,
  aud: Seq[String],
  exp: OffsetDateTime,
  nbf: OffsetDateTime,
  iat: OffsetDateTime,
  jti: String
) extends ApiModel


