#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

repository=$DOCKER_REPO

agreementManagementVersion="0.1"
catalogManagementVersion="0.1"
authorizationManagementVersion="0.1"
partyManagementVersion="0.1"
purposeManagementVersion="0.1"
userRegistryManagementVersion="0.1"
wellKnownURL=$WELL_KNOWN_URL
mainAudience=$MAIN_AUDIENCE

agreementManagementUrl="http://interop-be-agreement-management.interop-be-agreement-management.svc.cluster.local:8088/agreement-management/"$agreementManagementVersion
catalogManagementUrl="http://interop-be-catalog-management.interop-be-catalog-management.svc.cluster.local:8088/catalog-management/"$catalogManagementVersion
authorizationManagementUrl="http://interop-be-authorization-management.interop-be-authorization-management.svc.cluster.local:8088/authorization-management/"$authorizationmanagementVersion
partyManagementUrl="http://interop-be-party-management.interop-be-party-management.svc.cluster.local:8088/party-management/"$partyManagementVersion
purposeManagementUrl="http://interop-be-purpose-management.interop-be-purpose-management.svc.cluster.local:8088/party-management/"$purposeManagementVersion
userRegistryManagementUrl="http://pdnd-interop-uservice-user-registry-management.pdnd-interop-uservice-user-registry-management.svc.cluster.local:8088/pdnd-interop-uservice-user-registry-management/"$userRegistryManagementVersion

name=$(cat $SCRIPT_PATH/../build.sbt | grep "name :=" | awk -F:= '{ print $2 }' | sed 's/\"//' | sed 's/\",//' | sed 's/ //' | tr '[:upper:]' '[:lower:]' | grep -v client)
# Temporary solution
imageName=interop-be-authorization-process
#getting version from sbt
cd $SCRIPT_PATH/..
version=$(sbt -Dsbt.log.noformat=true 'inspect actual version' | grep "Setting: java.lang.String" | cut -d '=' -f2 | tr -d ' ')
cd $SCRIPT_PATH