/**
 * Security Process Micro Service
 * This service is the security supplier
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.authorizationprocess.client.api

import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model.KeysResponse
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.model.Problem
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker._
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.CollectionFormats._
import it.pagopa.pdnd.interop.uservice.authorizationprocess.client.invoker.ApiKeyLocations._

object WellKnownApi {

  def apply(baseUrl: String = "http://localhost/pdnd-interop-uservice-authorization-process/}") = new WellKnownApi(baseUrl)
}

class WellKnownApi(baseUrl: String) {
  
  /**
   * Returns PDND public keys.
   * 
   * Expected answers:
   *   code 200 : KeysResponse (PDND public keys in JWK format.)
   *   code 400 : Problem (Bad Request)
   */
  def getWellKnownKeys(): ApiRequest[KeysResponse] =
    ApiRequest[KeysResponse](ApiMethods.GET, baseUrl, "/.well-known/jwks.json", "application/json")
      .withSuccessResponse[KeysResponse](200)
      .withErrorResponse[Problem](400)
      



}

